### ISSUE TITLE
Feature 2: User can add entry to their favorites list

### ISSUE THREAD

**Issue by dennis-pnguyen** [dennis-pnguyen/PokeDen#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add their favorite pokemon to a list `favorites`.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

This portion of the application will allow users to view the pokemon entry and add them to a favorite's list.
## 🖼️ Wireframes

![Screenshot 2023-08-14 at 10 16 00 AM](https://github.com/dennis-pnguyen/ajax-project/assets/122412863/ee23d50b-38a5-45d0-b884-e6f63909cd93)
<img width="937" alt="Screenshot 2023-08-14 at 10 15 11 AM" src="https://github.com/dennis-pnguyen/ajax-project/assets/122412863/15a7f99f-31c9-4776-ba51-239b6a4756a1">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add anchor to home icon in order to refresh page
- [ ] Create 2 views `favorites` and `battle-list`. Use view swapping to switch between views
- [ ] Empty list view should display 'no pokemon have been added'
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
